


#define TBL_DESCRIPTOR_FILE "tables.xtxt"
#define TBL_DEBUG_PRINT 1
#define TBL_MAX_TABLE_NAME_LEN 3
#define TBL_MAX_FIELD_NAME_LEN 9
#define TBL_MAX_FIELD_VALUE_LEN 123
#define TBL_MAX_RECORD_SIZE 128
#define TBL_MAX_NUM_TABLES 1
#define TBL_MAX_TOTAL_NUM_FIELDS 2