on: [push]

name: Run Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: cd client && npm install && cd ../server && npm install && cd ..
      - run: npm run build --if-present
      - run: npm test